### ISSUE TITLE
handling peak files with bedtools

### ISSUE THREAD

**Issue by mistrm82** [hbctraining/Intro-to-ChIPseq-flipped#10]
- Introduce bedtools and discuss bed files (0 and 1 based files; but also connect it to narrowPeak/broadPeak files)
- First filter out blacklist regions (if we don't do this during alignment)
- Next, look at replicate concordance with a simple overlap (default parameters). Do this for WT and KO (provide snapshot peak files for KO in case they don't get through the exercise in peak calling)
- Finalize overlap peaks with more stringent criteria (Jihe tested various parameters and settled on this)

```
# Final code to generate the result
bedtools intersect -a WT_pair2_peaks_filtered.bed -b WT_pair3_peaks_filtered.bed -wo -f 0.3 -r > WT_bedtools_filtered_overlap_0.3.bed
```
- Create a set of confident peaks for WT and KO

**Comment by jihe-liu** [comment]
- Added blacklist filtering
- In the lesson, we identify overlap peaks between two replicates of WT sample. Currently, not dealing with KO sample. Do we still need to discuss that? Maybe as exercise?
