### ISSUE TITLE
Lesson 3 Comments

### ISSUE THREAD

**Issue by Gammerdinger** [hbctraining/Intro-to-ChIPseq-flipped#20]
Approximate time missing.

"Each quality score represents the probability that the corresponding nucleotide call is incorrect."

While this is true, I feel like this sentence might give people the impression that the relationship between quality score and probability that a nucleotide call is incorrect is a positive rather than inverse. The later table and equation rectifies this, but just some food for thought.

"NOTE: Before we run FastQC,..."

I think this note is good, but just a reminder if they weren't on a compute node in the previous module load FASTQC step, now that they are, FASTQC won't be loaded. Maybe move this up a few lines to double check before they load the module?

"$ fastqc -o ~/chipseq_workshop/results/fastqc/ ~/chipseq_workshop/data/wt_sample2_chip.fastq.gz"

Few things: 
1) I think the input directory should be raw_data instead of data
2) The folder doesn't have the WT sample in it. Just the KO samples.
3) The code dropdown in Exercise 1 also has these problems

**Comment by Gammerdinger** [comment]
Okay, the WT samples do exist. I tried to cp the files over without being in an interactive job and my command got cancelled.

**Comment by mistrm82** [comment]
moved the note as suggested
