### ISSUE TITLE
ChIP-seq Part II workshop

### ISSUE THREAD

**Issue by bcjonescbt** [hbctraining/Intro-to-ChIPseq-flipped#49]
In the ChIPseq flipped workshop, there are several references to more quantitative techniques to come in ChIP-seq Part II workshop.

It is mentioned three times on this page:
https://github.com/hbctraining/Intro-to-ChIPseq-flipped/blob/main/lessons/09_data_visualization.md

Is this second workshop in a different repository? I can't seem to find it.

Thanks for sharing such a great resource!

**Comment by mistrm82** [comment]
Hi @bcjonescbt ,

thanks for checking.  Unfortunately, the part II workshop development is temporarily on hold for now and there is no additional repository. We recommend R-based tools like DiffBind, and ChIPseeker for downstream analyses; each of them have very detailed vignettes that are helpful.
