### ISSUE TITLE
Flesh out FASTQC 

### ISSUE THREAD

**Issue by mistrm82** [hbctraining/Intro-to-ChIPseq-flipped#5]
- talk more about what you typically see in the QC plots for ChIP seq data
- take some material from the troubleshooting slide deck (it's okay to have some redundancy with the summary at end of course)

**Comment by mistrm82** [comment]
Take out the sequencing (SBS) content video and put it in self-learning/pre-reading

**Comment by mistrm82** [comment]
For the code:
- run fastqc on all samples to show how it works
- then log out and log in with multlple cores to run multithreading 

Right now the lesson has this all in one continuous chunk of code:

```
$ exit  #exit the current interactive session

$ srun --pty -c 6 -p interactive -t 0-12:00 --mem 1G --reservation=HBC2 /bin/bash  #start a new one with 6 cpus (-n 6) and 1G RAM (--mem 1G)

$ module load fastqc/0.11.5  #reload the module for the new session

$ cd ~/chipseq/raw_data

$ fastqc -t 6 *.fastq  #note the extra parameter we specified for 6 threads
```
We need to include more text describing each step (the way we do in RNA-seq).

**Comment by mistrm82** [comment]
Flesh out the section on going through the QC report. Have relevant images followed by text. Maybe an exercise question  or two on interpretation of plots for those not described in lesson (i.e. KO sample)?

**Comment by jihe-liu** [comment]
One question: in fastqc report, "Per base sequence composition" is no longer a metric?

**Comment by jihe-liu** [comment]
- Shall we use only the relative path, so that the code does not look overwhelming?
