### ISSUE TITLE
no links for chipseq

### ISSUE THREAD

**Issue by eberdan** [hbctraining/Intro-to-ChIPseq-flipped#50]
there seems to be something wrong with the main html page for the chromatin workshop: https://hbctraining.github.io/Intro-to-ChIPseq-flipped/. There are no links to click (i.e. trainer led workshop or self learning)

**Comment by mistrm82** [comment]
Created md: https://github.com/hbctraining/Intro-to-ChIPseq-flipped/blob/main/schedule/links-to-lessons.md

 and linked!
