### ISSUE TITLE
Negative controls in Cut and Run

### ISSUE THREAD

**Issue by hwick** [hbctraining/Intro-to-ChIPseq-flipped#52]
There seems to be some debate about whether IgG or chromatin input is best for negative control in Cut and Run. A quick google seems to suggest that most people recommend using IgG for peak calling, however there are a few notes of dissent that bring up interesting points. Additionally, some mention use of a positive control, such as a histone mod. Ultimately it may be best to go with whatever is recommended by the maker of the kit being used. 

Anti-IgG, pro chromatin input for Cut and Run:
https://www.cellsignal.com/learn-and-support/frequently-asked-questions/cut-and-run-faqs#a22
(q22 is about cut and run qPCR, there is a similar note under cut and run NGS a few questions below)

Anti-IgG, pro chromatin input for ChIPseq; not sure if this would be applicable for cut and run as well, but it is a similar sentiment as mentioned on the cellsignal site:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3541830/#:~:text=While%20both%20non%2Dspecific%20IgGs,pull%20down%20much%20less%20DNA
"IgGs usually pull down much less DNA than a specific antibody and thus limited genomic regions from the control may be over-amplified during the library construction step. In this case the resulting sequence reads will not sufficiently cover the genome as a background model for peak identification. Therefore, chromatin inputs serve as better controls for bias in chromatin fragmentation and variations in sequencing efficiency; additionally, they provide greater and more evenly distributed coverage of the genome."

Pro IgG for Cut and Run:
https://hbctraining.github.io/Intro-to-ChIPseq-flipped/CUT&RUN/Intro_to_CUT&RUN.html#:~:text=However%2C%20CUT%26RUN%20is%20thought%20to,low%20efficiency%20without%20sequence%20bias.

**Comment by mistrm82** [comment]
Added a note and link to https://github.com/hbctraining/Intro-to-ChIPseq-flipped/blob/main/lessons/01b_experimental_design_considerations.md
