### ISSUE TITLE
Create an "Aligning reads for ChIP-seq" markdown

### ISSUE THREAD

**Issue by mistrm82** [hbctraining/Intro-to-ChIPseq-flipped#7]
- Do not need Alignment theory slides -- take what we need and add it to this markdown where relevant 
 https://github.com/hbctraining/Intro-to-ChIPseq/blob/master/lectures/alignment_theory.pdf

**Comment by mistrm82** [comment]
For code:

- use mm10 as the reference genome (bowtie2 index will be made available)
- Present the code for bowtie2 on a single sample (but have a #DO NOT RUN). Use this time to  discuss the parameters. Running a single sample interactively will be a long wait
- Exercise: create a job submission script to run bowtie2 on a single sample (WT rep1; this has a lower alignment rate ~60-70%). This will be the first job submission script so provide guidance on the different SBATCH options. This same sample shows lower signal in profile plots. We will want to discuss this later with data viz. Another exercise question - look at your .err file - comment on the alignment rate 
- Describe SAM/BAM file
- Turn SAM (default output) into BAM file. Present code for samtools; discuss samtools and also the need for smaller file
- Have a note that we are not actually using the SAM file, and we could (in theory) delete it. In automation we will pipe so that we do not create this intermediate file
- After the alignment, also need to index the final bam files. 
```
for file in *.bam do echo "processing $file" samtools index $file done
```

**Comment by mistrm82** [comment]
The "Creating and index" can be updated such that the current note on shared databases can become main text. We will not be providing them a reference instead they will be pointing to `/n/groups/shared_databases/bowtie2_indexes/mm10 `

**Comment by mistrm82** [comment]
@marypiper I have fleshed out some things (adding content from slide deck) and reorganized the lesson, in addition to @jihe-liu modifications. I have some comments where you might need to add some content or trim things, but it's all yours from here.

**Comment by marypiper** [comment]
Updated the content
