### ISSUE TITLE
Create a filtering reads markdown 

### ISSUE THREAD

**Issue by mistrm82** [hbctraining/Intro-to-ChIPseq-flipped#8]
Add blacklist filtering here

**Comment by mistrm82** [comment]
use bedtools as we do in bcbio:

`bedtools intersect -abam reads.bam -b sample.bed -v `

**Comment by mistrm82** [comment]
we will do this post-peak calling instead

**Comment by mistrm82** [comment]
Some notes:
- We have removed the SAM to BAM step, as it made more sense to do that in the alignment lesson where we talk about alignment filetypes
- Only run this on one sample (WT rep1 from alignment)
- Feels like an awfully short lesson. Think about what we could add to give it more - maybe add blacklist filtering with the use of samtools/sambamba? @jihe-liu will check/test and report back

**Comment by mistrm82** [comment]
Talk about an index for the BAM file and then run code to create it

**Comment by jihe-liu** [comment]
We finally decide to not running the black-list filtering here, but instead after peak calling. While the sorting command is running (7 min), we could talk about the black-list, and the difference of filtering here with the BAM file, compared to filtering later with the bed file.
